### PR TITLE
Support aerial

### PR DESCRIPTION
**Pull request by Isrothy**
Support aerial https://github.com/stevearc/aerial.nvim

### CODE REVIEW

**Comment by gbprod** [comment]
Thanks for your PR !
Can you provide a screenshot ?

**Comment by gbprod** [comment]
Thanks for your PR !
Can you provide a screenshot ?

**Comment by Isrothy** [comment]
Yes!
It should look like this
image
I can change them if you are not satisfied with some highlights.

**Comment by gbprod** [comment]
Look awesome ! Thanks !

**Comment by gbprod** [comment]
What plugin do you use to colorize brackets ?

**Comment by Isrothy** [comment]
p00f/nvim-ts-rainbow

**Pull request merged**
