### PR TITLE
Add initial support for sindrets/diffview.nvim

### PR DESCRIPTION
**Pull request by przepompownia**
At this moment it only changes highlights for file history panel.

### CODE REVIEW

**Comment by przepompownia** [comment]
At this moment it only changes highlights for file history panel:
Before:
image
After:
image

**Comment by przepompownia** [comment]
For diff content diffview.nvim uses built-in highlight groups (`DiffviewDiffAdd` links to `DiffAdd` etc.). @gbprod what do you think about change `Diff*` to something more subtle? Currently built-in diff view looks like above:
image

**Comment by gbprod** [comment]
Hi @przepompownia, thanks for this PR, it seems nice.

What are you thinking about when you say `something more subtle` ?
You can configure diff colors using   `diff.mode` option (I think that it looks better with the `fg` value :) )

**Comment by gbprod** [comment]
Nice!
Can you create a PR with this change?

**Comment by przepompownia** [comment]
Thanks for merging. Starting to look for practical use of this tool for myself I focused on file history panel only.

> Nice! Can you create a PR with this change?

#37

**Pull request merged**
